# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'page_r1.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_r1(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(506, 869)
        self.listView = QtWidgets.QListView(Form)
        self.listView.setGeometry(QtCore.QRect(0, 0, 511, 871))
        self.listView.setStyleSheet("border-image: url(:/image/4.png);")
        self.listView.setObjectName("listView")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(100, 60, 311, 161))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Century")
        font.setPointSize(48)
        self.label.setFont(font)
        self.label.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(100, 670, 311, 51))
        font = QtGui.QFont()
        font.setFamily("Century")
        font.setPointSize(15)
        self.pushButton.setFont(font)
        self.pushButton.setFlat(True)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(160, 740, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Century")
        font.setPointSize(15)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")

        self.listView_3 = QtWidgets.QListView(Form)
        self.listView_3.setEnabled(True)
        self.listView_3.setGeometry(QtCore.QRect(90, 370, 130, 130))
  #      self.listView_3.setStyleSheet("border-image: url(:/image/5.png);")
        self.listView_3.setObjectName("listView_3")

        self.listView_5 = QtWidgets.QListView(Form)
        self.listView_5.setEnabled(True)
        self.listView_5.setGeometry(QtCore.QRect(290, 370, 130, 130))
        # self.listView_5.setStyleSheet("border-image: url(:/image/5.png);")
        self.listView_5.setObjectName("listView_5")

        self.listView_6 = QtWidgets.QListView(Form)
        self.listView_6.setEnabled(True)
        self.listView_6.setGeometry(QtCore.QRect(90, 530, 130, 130))
        # self.listView_6.setStyleSheet("border-image: url(:/image/5.png);")
        self.listView_6.setObjectName("listView_6")

        self.listView_7 = QtWidgets.QListView(Form)
        self.listView_7.setEnabled(True)
        self.listView_7.setGeometry(QtCore.QRect(290, 530, 130, 130))
        # self.listView_7.setStyleSheet("border-image: url(:/image/5.png);")
        self.listView_7.setObjectName("listView_7")

        self.listView_8 = QtWidgets.QListView(Form)
        self.listView_8.setEnabled(True)
        self.listView_8.setGeometry(QtCore.QRect(290, 210, 130, 130))
        # self.listView_8.setStyleSheet("border-image: url(:/image/5.png);")
        self.listView_8.setObjectName("listView_8")

        self.listView_2 = QtWidgets.QListView(Form)
        self.listView_2.setEnabled(True)
        self.listView_2.setGeometry(QtCore.QRect(90, 210, 130, 130))
        # self.listView_2.setStyleSheet("border-image: url(:/image/5.png);")
        self.listView_2.setObjectName("listView_2")

        self.retranslateUi(Form)
        self.pushButton.clicked.connect(Form.show_message_1) # type: ignore
        self.pushButton_2.clicked.connect(Form.return_to_2) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Lab2_Bobing"))
        self.label.setText(_translate("Form", "Result"))
        self.pushButton.setText(_translate("Form", "Display the results"))
        self.pushButton_2.setText(_translate("Form", "Play it again!"))
import picture
