# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'page1.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_1(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(499, 875)
        self.page1_listView = QtWidgets.QListView(Form)
        self.page1_listView.setGeometry(QtCore.QRect(0, 0, 501, 881))
        self.page1_listView.setStyleSheet("border-image: url(:/image/1.png);")
        self.page1_listView.setObjectName("page1_listView")
        self.start_button = QtWidgets.QPushButton(Form)
        self.start_button.setGeometry(QtCore.QRect(80, 500, 131, 51))
        font = QtGui.QFont()
        font.setFamily("Century")
        font.setPointSize(15)
        self.start_button.setFont(font)
        self.start_button.setObjectName("start_button")
        self.rule_button = QtWidgets.QPushButton(Form)
        self.rule_button.setGeometry(QtCore.QRect(280, 500, 131, 51))
        font = QtGui.QFont()
        font.setFamily("Century")
        font.setPointSize(15)
        self.rule_button.setFont(font)
        self.rule_button.setObjectName("rule_button")

        self.retranslateUi(Form)
        self.rule_button.clicked.connect(Form.page1_2) # type: ignore
        self.start_button.clicked.connect(Form.page1_3) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Lab2_Bobing"))
        self.start_button.setText(_translate("Form", "Start"))
        self.rule_button.setText(_translate("Form", "Rules"))
import picture
