# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'page4.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_4(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(510, 878)
        Form.setStyleSheet("")
        self.page_4_listView = QtWidgets.QListView(Form)
        self.page_4_listView.setGeometry(QtCore.QRect(0, 0, 511, 881))
        self.page_4_listView.setStyleSheet("border-image: url(:/image/4.png);")
        self.page_4_listView.setObjectName("page_4_listView")
        self.stop_Button = QtWidgets.QPushButton(Form)
        self.stop_Button.setGeometry(QtCore.QRect(100, 680, 311, 51))
        font = QtGui.QFont()
        font.setFamily("Century")
        font.setPointSize(15)
        self.stop_Button.setFont(font)
        self.stop_Button.setStyleSheet("")
        self.stop_Button.setFlat(True)
        self.stop_Button.setObjectName("stop_Button")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(80, 140, 341, 121))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Century")
        font.setPointSize(33)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("")
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(140, 380, 240, 200))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Form)
        self.stop_Button.clicked.connect(Form.page4_r1) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Lab2_Bobing"))
        self.stop_Button.setText(_translate("Form", "Stop!"))
        self.label.setText(_translate("Form", "Beginning!"))
import picture
