# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'page_r2.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_r2(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(500, 871)
        self.listView = QtWidgets.QListView(Form)
        self.listView.setGeometry(QtCore.QRect(0, 0, 501, 871))
        self.listView.setStyleSheet("border-image: url(:/image/4.png);")
        self.listView.setObjectName("listView")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(90, 80, 311, 161))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Century")
        font.setPointSize(56)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(110, 740, 281, 41))
        font = QtGui.QFont()
        font.setFamily("Century")
        font.setPointSize(15)
        self.pushButton.setFont(font)
        self.pushButton.setFlat(False)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(110, 670, 281, 51))
        font = QtGui.QFont()
        font.setFamily("Century")
        font.setPointSize(15)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setFlat(True)
        self.pushButton_2.setObjectName("pushButton_2")
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(60, 240, 381, 411))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.listView_2 = QtWidgets.QListView(self.layoutWidget)
        self.listView_2.setStyleSheet("border-image: url(:/image/5.png);")
        self.listView_2.setObjectName("listView_2")
        self.gridLayout.addWidget(self.listView_2, 0, 0, 1, 1)
        self.listView_7 = QtWidgets.QListView(self.layoutWidget)
        self.listView_7.setStyleSheet("border-image: url(:/image/5.png);")
        self.listView_7.setObjectName("listView_7")
        self.gridLayout.addWidget(self.listView_7, 2, 1, 1, 1)
        self.listView_6 = QtWidgets.QListView(self.layoutWidget)
        self.listView_6.setStyleSheet("border-image: url(:/image/5.png);")
        self.listView_6.setObjectName("listView_6")
        self.gridLayout.addWidget(self.listView_6, 2, 0, 1, 1)
        self.listView_4 = QtWidgets.QListView(self.layoutWidget)
        self.listView_4.setStyleSheet("border-image: url(:/image/5.png);")
        self.listView_4.setObjectName("listView_4")
        self.gridLayout.addWidget(self.listView_4, 1, 0, 1, 1)
        self.listView_3 = QtWidgets.QListView(self.layoutWidget)
        self.listView_3.setStyleSheet("border-image: url(:/image/5.png);")
        self.listView_3.setObjectName("listView_3")
        self.gridLayout.addWidget(self.listView_3, 0, 1, 1, 1)
        self.listView_5 = QtWidgets.QListView(self.layoutWidget)
        self.listView_5.setStyleSheet("border-image: url(:/image/5.png);")
        self.listView_5.setObjectName("listView_5")
        self.gridLayout.addWidget(self.listView_5, 1, 1, 1, 1)

        self.retranslateUi(Form)
        self.pushButton.clicked.connect(Form.return_to_1) # type: ignore
        self.pushButton_2.clicked.connect(Form.show_message_2) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Lab2_Bobing"))
        self.label.setText(_translate("Form", "Result"))
        self.pushButton.setText(_translate("Form", "Play it again!"))
        self.pushButton_2.setText(_translate("Form", "Display the results"))
import picture
